version: '3.8'
services:
    fe.next.bemsocial:
        container_name: fe.next.bemsocial
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        restart: always
        networks:
            - bemsocial-network

networks:
    bemsocial-network:
        external: true
