services:
  postgres:
    image: postgres:15
    container_name: bemsocial.postgres
    ports:
      - ${DB_PORT}:5432 #{port in host(myPC) : (port in Container)}
    environment: #enviroment variables, like: db's username, password...
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - bemsocial-network

  be.nest.bemsocial:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be.nest.bemsocial
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: ${DATABASE_URL}
    # command: sh -c "npx prisma migrate dev && yarn start:dev"
    networks:
      - bemsocial-network

networks:
  bemsocial-network:
    external: true
