services:
  postgres:
    image: postgres:15
    container_name: bemsocial.postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bemsocial-network

  be.nest.bemsocial:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be.nest.bemsocial
    ports:
      - ${PORT}:${PORT}
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate dev --name init && yarn start:dev"
    networks:
      - bemsocial-network

volumes:
  postgres_data:

networks:
  bemsocial-network:
    driver: bridge
