version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: ../docker/dockerfiles/api-gateway.Dockerfile
    container_name: bem_social_api_gateway
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DATABASE=bem_social
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=1d
      - AUTH_SERVICE_URL=auth-service:3001
      - USER_SERVICE_URL=user-service:3002
      - POST_SERVICE_URL=post-service:3003
      - NOTIFICATION_SERVICE_URL=notification-service:3004
      - FEED_SERVICE_URL=feed-service:3005
      - SEARCH_SERVICE_URL=search-service:3006
    depends_on:
      - postgres
      - redis
      - auth-service
    networks:
      - bem_social_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Auth Service
  auth-service:
    build:
      context: ../services/auth-service
      dockerfile: ../../docker/dockerfiles/auth-service.Dockerfile
    container_name: bem_social_auth_service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DATABASE=bem_social_auth
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=1d
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - bem_social_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Database
  postgres:
    image: postgres:14
    container_name: bem_social_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: bem_social,bem_social_auth,bem_social_user,bem_social_post,bem_social_notification,bem_social_feed,bem_social_search
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    networks:
      - bem_social_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  # Redis (for caching và rate limiting)
  redis:
    image: redis:7
    container_name: bem_social_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bem_social_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Nginx (for load balancing and SSL termination)
  nginx:
    image: nginx:latest
    container_name: bem_social_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api-gateway
    networks:
      - bem_social_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  bem_social_network:
    driver: bridge 